[2016-01-05 20:51:26,697] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:26,796] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:51:26,798] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:48,243] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:48,390] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:51:48,394] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:48,482] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:51:48,483] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:58,189] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:58,391] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:51:58,392] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:58,434] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:51:58,435] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:53:41,169] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:53:41,315] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:53:41,316] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:53:41,394] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:53:41,395] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:54:28,224] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:54:28,454] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:54:28,456] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:54:28,497] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:54:28,498] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:51,506] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:51,708] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:55:51,709] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:51,762] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:55:51,763] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:53,820] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:54,061] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:55:54,064] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:55:54,110] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:55:54,111] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:52,833] {main.py-><module>:135} INFO - 



******************[93m2016-01-05 20:56:52.833027[39m*******************
[2016-01-05 20:56:53,356] {main.py-><module>:135} INFO - 



******************[93m2016-01-05 20:56:53.356288[39m*******************
[2016-01-05 20:56:55,485] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:55,625] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:56:55,629] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:55,698] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:56:55,699] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:57,167] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:57,372] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:56:57,375] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:56:57,423] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:56:57,425] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:57:03,195] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:57:03,616] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:57:03,682] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:57:03,682] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:57:03,738] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:57:03,739] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:57:03,852] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:57:03,854] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 21:04:21,961] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 21:04:22,129] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 21:04:22,130] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 21:04:22,257] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 21:04:22,258] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 21:04:32,366] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
